AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a TaskSet

Parameters:
  DeploymentGroup:
    Type: String
    AllowedValues:
      - Blue
      - Green
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select at two subnets in your selected VPC.  

Conditions:
  DeploymentGroup: !Equals [ !Ref DeploymentGroup, Blue ]

Resources:
  TaskSet:
    Type: AWS::ECS::TaskSet
    Properties:
      Cluster:
        Fn::ImportValue: ECSCluster
      Service:
        Fn::ImportValue: ECSService
      Scale:
        Unit: PERCENT
        Value: 100
      TaskDefinition:
        Fn::If:
        - DeploymentGroup
        - Fn::ImportValue:
            BlueTaskDefinition
        - Fn::ImportValue:
            GreenTaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          TargetGroupArn:
            Fn::If:
            - DeploymentGroup
            - Fn::ImportValue:
                BlueServiceTargetGroup
            - Fn::ImportValue:
                GreenServiceTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - Fn::ImportValue:  ServiceSecurityGroup
          Subnets: !Ref Subnets
